Upgrade Spring version to Spring5
AlexKolonitsky/TimesheetManagement pull request #11
Opened 2019-03-14 11:50 UTC by TicTacT0e

Versions of spring-core and spring-context was changed to 5.1.5.RELEASE. Added up some spring-boot dependencies for spring 5 and jersey integration via spring-boot-starter. 

Removed deployment descriptor. Also added up JerseyConfig.class in "config" package. In this class registred jax-rs resource classes and supplied root path of web application.

2019-03-15 06:16 UTC, AlexKolonitsky requested changes

2019-03-15 06:16 UTC, AlexKolonitsky commented on pom.xml
> +            <version>5.1.5.RELEASE</version>
вынеси в property

2019-03-15 06:16 UTC, AlexKolonitsky commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
Делай это не через spring boot a через spring mvc пока

2019-03-16 13:41 UTC, TicTacT0e commented on pom.xml
> +            <version>5.1.5.RELEASE</version>
сделал

2019-03-16 13:41 UTC, TicTacT0e commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
и это тоже сделал

2019-03-16 13:45 UTC, TicTacT0e commented
Попробовал решить конфликты в отдельной ветке от последнего коммита в мастере, с помощью merge --squash. Ее бы и отправил в пул реквест, но тогда он бы не появился на to do board. 
В общем, эту ветку я просто смерджил с той, где решал конфликты, вроде все поправил.

2019-03-19 18:05 UTC, AlexKolonitsky requested changes

2019-03-19 18:05 UTC, AlexKolonitsky commented on pom.xml
> +                <artifactId>spring-boot-maven-plugin</artifactId>
remove

2019-03-19 18:05 UTC, AlexKolonitsky commented on src/main/java/app/config/ApplicationInitializer.java
> +import org.springframework.web.context.request.RequestContextListener;
зачем,?

2019-03-19 18:28 UTC, TicTacT0e commented on pom.xml
> +                <artifactId>spring-boot-maven-plugin</artifactId>
удалил

2019-03-19 18:28 UTC, TicTacT0e commented on src/main/java/app/config/ApplicationInitializer.java
> +import org.springframework.web.context.request.RequestContextListener;
ну он же не мешал
но я удалил

2019-03-19 18:39 UTC, AlexKolonitsky approved these changes

2019-03-20 10:16 UTC, merged