Modified project
AlexKolonitsky/TimesheetManagement pull request #115
Opened 2019-06-19 20:16 UTC by AlenaChuvasova

2019-06-20 10:33 UTC, KirylShalpuk requested changes

2019-06-20 10:33 UTC, KirylShalpuk commented on src/main/java/app/dao/impl/ProjectDaoImpl.java
> +    private static final String GET_PROJECT_TEAM_QUERY = "select empl.name, empl.photoUrl from Employee empl join Assignment assign on empl.id = assign.employeeId join Project proj on proj.id = assig
что-то мне кажется здесь с checkstyle проблемы будут. строка не должна быть более 80 символов

2019-06-20 10:36 UTC, KirylShalpuk commented on src/main/java/app/dao/impl/ProjectDaoImpl.java
> +    private static final String GET_PROJECT_TEAM_QUERY = "select empl.name, empl.photoUrl from Employee empl join Assignment assign on empl.id = assign.employeeId join Project proj on proj.id = assig
You have 16 Checkstyle violations

2019-06-24 01:55 UTC, TicTacT0e approved these changes

2019-06-24 05:33 UTC, KirylShalpuk approved these changes

2019-06-24 05:34 UTC, merged