Dependencies for integration/company/notification/employee
AlexKolonitsky/TimesheetManagement pull request #119
Opened 2019-06-24 06:08 UTC by AlenaChuvasova

2019-06-29 16:42 UTC, igorkraskovskiii requested changes

2019-06-29 16:42 UTC, igorkraskovskiii commented on src/main/java/app/entities/Timesheet.java
> +    @Override
вставь пожалуйста equals и hashCode после всех методов

2019-06-30 17:44 UTC, TicTacT0e approved these changes

2019-06-30 18:12 UTC, igorkraskovskiii approved these changes

2019-06-30 18:12 UTC, merged