Db schema
AlexKolonitsky/TimesheetManagement pull request #12
Opened 2019-03-14 18:49 UTC by AlenaChuvasova

2019-03-15 06:20 UTC, AlexKolonitsky requested changes

2019-03-15 06:20 UTC, AlexKolonitsky commented on db/project_scheme.sql
> +  PRIMARY KEY (`id`)
@AlenaChuvasova Внимательно пересмотри размеры полей code - 6, colour - 6, description - больше, logoUrl - сравни со всеми остальными

2019-03-15 06:20 UTC, AlexKolonitsky commented on db/project_scheme.sql
> +status varchar(25) NOT NULL
поправьте табуляцию

2019-04-11 21:16 UTC, igorkraskovskiii commented on db/project_scheme.sql
> +  UNIQUE KEY `PhotoUrlEmailPhoneName_UNIQUE` (`photoUrl`,`email`,`phone`,`name`)
возможно, мне следовало сделать так:
UNIQUE KEY `PhotoUrlPhoneName_UNIQUE` (`photoUrl`,`phone`,`name`),
UNIQUE KEY `Email_UNIQUE` (`email`)

2019-04-11 21:18 UTC, igorkraskovskiii commented on db/project_scheme.sql
> +  UNIQUE KEY `NameCompanyId_UNIQUE` (`companyId`,`name`),
а здесь так
UNIQUE KEY `CodeLogoUrlCompanyIdName_UNIQUE` (`code`,`logoUrl`,`companyId`,`name`),

2019-04-16 18:45 UTC, AlexKolonitsky approved these changes

2019-04-16 18:45 UTC, merged