Log4j add
AlexKolonitsky/TimesheetManagement pull request #18
Opened 2019-03-17 11:16 UTC by shieran

log4j installation

2019-03-19 18:06 UTC, AlexKolonitsky requested changes

2019-03-19 18:06 UTC, AlexKolonitsky commented on pom.xml
> -    <reporting>
вернуть

2019-03-20 19:43 UTC, shieran commented on pom.xml
> -    <reporting>
reporting returned

2019-03-20 19:47 UTC, shieran commented
вернул reporting, добавил пример, чтобы посмотреть как работает логер. Версию джавы менял, но вернул обратно

2019-03-21 18:24 UTC, AlexKolonitsky approved these changes

2019-03-23 08:52 UTC, merged