Hibernate crud invitation
AlexKolonitsky/TimesheetManagement pull request #60
Opened 2019-04-26 11:07 UTC by KirylShalpuk

included hibernate to CRUD for Invitation

2019-05-11 16:17 UTC, AlexKolonitsky requested changes

2019-05-11 16:17 UTC, AlexKolonitsky commented on src/main/java/app/dao/impl/InvitationDaoImpl.java
> +@Transactional
убрать

2019-05-11 16:17 UTC, AlexKolonitsky commented on src/main/java/app/config/beans/HibernateConfig.java
> +    private String showSql;
revert

2019-05-11 16:34 UTC, KirylShalpuk commented on src/main/java/app/config/beans/HibernateConfig.java
> +    private String showSql;
completed

2019-05-11 16:34 UTC, KirylShalpuk commented on src/main/java/app/dao/impl/InvitationDaoImpl.java
> +@Transactional
completed

2019-05-16 18:48 UTC, AlexKolonitsky approved these changes

2019-05-16 18:48 UTC, merged