Tests for crud invitation
AlexKolonitsky/TimesheetManagement pull request #61
Opened 2019-04-26 11:08 UTC by KirylShalpuk

added tests for crud invitation

2019-05-03 18:46 UTC, AlexKolonitsky requested changes

2019-05-03 18:46 UTC, AlexKolonitsky commented on pom.xml
> +        <maven.compiler.source>1.9</maven.compiler.source>
return

2019-05-03 18:46 UTC, AlexKolonitsky commented on pom.xml
> +        <slf4j.version>1.7.26</slf4j.version>
revert

2019-05-03 18:46 UTC, AlexKolonitsky commented on src/test/java/app/dao/impl/Invitation/DeleteInvitationDaoTest.java
> +            IDataSet iDataSet = new FlatXmlDataSetBuilder().build(getClass().getClassLoader()
common method

2019-05-03 18:46 UTC, AlexKolonitsky commented on src/test/java/app/dao/impl/Invitation/GetFinfByIdInvitationDaoTest.java
> +//    public void getFindByIdException() {
remove

2019-05-03 20:18 UTC, KirylShalpuk commented on pom.xml
> +        <maven.compiler.source>1.9</maven.compiler.source>
completed

2019-05-03 20:20 UTC, KirylShalpuk commented on src/test/java/app/dao/impl/Invitation/GetFinfByIdInvitationDaoTest.java
> +//    public void getFindByIdException() {
completed

2019-05-03 20:30 UTC, KirylShalpuk commented on pom.xml
> +        <slf4j.version>1.7.26</slf4j.version>
completed

2019-05-04 05:47 UTC, KirylShalpuk commented on src/test/java/app/dao/impl/Invitation/DeleteInvitationDaoTest.java
> +            IDataSet iDataSet = new FlatXmlDataSetBuilder().build(getClass().getClassLoader()
completed

2019-05-04 12:09 UTC, AlexKolonitsky requested changes

2019-05-04 12:09 UTC, AlexKolonitsky commented on pom.xml
> +
remove changes

2019-05-04 12:09 UTC, AlexKolonitsky commented on pom.xml
> +</project>
remove changes

2019-05-04 12:09 UTC, AlexKolonitsky commented on src/main/java/app/config/JerseyConfig.java
>      }
remove changes

2019-05-04 12:09 UTC, AlexKolonitsky commented on src/test/resources/project.properties
>  artifactId=${project.artifactId}
remove changes

2019-05-04 12:50 UTC, KirylShalpuk commented on src/main/java/app/config/JerseyConfig.java
>      }
completed

2019-05-04 12:50 UTC, KirylShalpuk commented on pom.xml
> +</project>
completed

2019-05-04 12:50 UTC, KirylShalpuk commented on pom.xml
> +
completed

2019-05-04 12:52 UTC, KirylShalpuk commented
completed correct yours remarks

2019-05-16 18:08 UTC, closed without merging