Crud logs hibernate
AlexKolonitsky/TimesheetManagement pull request #66
Opened 2019-05-03 13:52 UTC by igorkraskovskiii

2019-05-03 18:39 UTC, AlexKolonitsky requested changes

2019-05-03 18:39 UTC, AlexKolonitsky commented on src/main/java/app/resources/LogsResource.java
> +/*    @GET
remove comment

2019-05-04 11:23 UTC, igorkraskovskiii commented on src/main/java/app/resources/LogsResource.java
> +/*    @GET
made

2019-05-04 12:20 UTC, AlexKolonitsky requested changes

2019-05-04 12:20 UTC, AlexKolonitsky commented on pom.xml
> +        <db.url>jdbc:mysql://localhost:3306/timesheetmanager</db.url>
remove changes

2019-05-04 12:21 UTC, AlexKolonitsky requested changes

2019-05-04 12:21 UTC, AlexKolonitsky commented on src/test/resources/input.xml
> +    <activity id="1" name="serg"/>
remove comments

2019-05-04 12:33 UTC, igorkraskovskiii commented on pom.xml
> +        <db.url>jdbc:mysql://localhost:3306/timesheetmanager</db.url>
fixed

2019-05-04 12:34 UTC, igorkraskovskiii commented on pom.xml
> +        <db.url>jdbc:mysql://localhost:3306/timesheetmanager</db.url>
fixed

2019-05-04 12:34 UTC, igorkraskovskiii commented on src/test/resources/input.xml
> +    <activity id="1" name="serg"/>
fixed

2019-05-04 13:01 UTC, AlexKolonitsky approved these changes

2019-05-04 13:01 UTC, AlexKolonitsky commented on pom.xml
> -        <dependency>
why you remove slf4j ?

2019-05-04 13:01 UTC, merged