Tests for assignment crud
AlexKolonitsky/TimesheetManagement pull request #74
Opened 2019-05-09 23:01 UTC by TicTacT0e

2019-05-16 17:53 UTC, AlexKolonitsky requested changes

2019-05-16 17:53 UTC, AlexKolonitsky commented on src/test/java/app/dao/impl/AssignmentDaoImplTests.java
> +                    .getResourceAsStream("tests.properties")));
use project properties file

2019-05-19 14:06 UTC, TicTacT0e commented on src/test/java/app/dao/impl/AssignmentDaoImplTests.java
> +                    .getResourceAsStream("tests.properties")));
Исправил

2019-05-21 18:01 UTC, AlexKolonitsky approved these changes

2019-05-21 18:01 UTC, merged