Test connection
AlexKolonitsky/TimesheetManagement pull request #96
Opened 2019-05-23 13:07 UTC by ilia119

2019-05-27 15:42 UTC, AlexKolonitsky requested changes
pull changes from master

2019-05-28 09:00 UTC, ilia119 commented
> pull changes from master

done

2019-05-29 10:57 UTC, AlexKolonitsky reviewed
забери изменения из мастера

2019-05-29 12:09 UTC, ilia119 commented
> забери изменения из мастера

забрал

2019-06-04 18:31 UTC, AlexKolonitsky requested changes

2019-06-04 18:31 UTC, AlexKolonitsky commented on src/main/java/app/entities/Notification.java
> +    private int partnerId;
нету у нас partner сущности

2019-06-04 18:38 UTC, ilia119 commented on src/main/java/app/entities/Notification.java
> +    private int partnerId;
исправил

2019-06-04 18:47 UTC, AlexKolonitsky approved these changes

2019-06-04 18:47 UTC, merged